$homeurl="https://www.octanetworks.com";$suffix=".html";function validate(){var pass=$("#password").val();var c_pass=$("#confirm_pass").val();if(pass===c_pass){return!0}else{alert("Password Doesnt Match");return!1}}$(function(){$(document).delegate(".add_cart","click",function(){$id=$(this).data("id");$type=$(this).data("product");$dur=$(this).data("duration");$url=$(this).data("url");$.ajax({type:"POST",url:$url,data:{id:$id,type:$type,dur:$dur},dataType:"json",traditional:!0,success:function(response){if(response.status==="ok"){window.location=response.url}
if(response.status==="error"){}},error:function(response){alert(response)}})});$(document).delegate(".subscribe","click",function(){$email=$("#email").val();$action=$("#action").val();$url=$homeurl+"/main/forms/newsletter"+$suffix;var $form=$(this);$.ajax({type:"POST",url:$url,data:{email:$email,action:$action},dataType:"json",traditional:!0,success:function(response){if(response.status==="ok"){$('#newslettermsg').html(response.msg);$("#newsModal").modal('show')}if(response.status==="error"){}},error:function(response){alert(response)}})});$(document).delegate(".delete_cart","click",function(){$id=$(this).data("id");$url=$(this).data("url");$.ajax({type:"POST",url:$url,data:{id:$id},dataType:"json",traditional:!0,success:function(response){if(response.status==="ok"){window.location=response.url}if(response.status==="error"){}},error:function(response){alert(response)}})});$(document).delegate(".apply_coupon","click",function(){$code=$("#coupon").val();$url=$homeurl+"/main/cart/apply_coupon"+$suffix;$.ajax({type:"POST",url:$url,data:{code:$code},dataType:"json",traditional:!0,success:function(response){if(response.status==="ok"){window.location=response.url}
if(response.status==="error"){}},error:function(response){alert(response)}})});$(document).delegate(".update_qty","click",function(){var $myid='#txtqty'+$(this).data("counter");$qty=$($myid).val();$id=$(this).data("id");$url=$homeurl+"/main/cart/update_qty"+$suffix;var $form=$(this);$.ajax({type:"POST",url:$url,data:{qty:$qty,id:$id},dataType:"json",traditional:!0,success:function(response){if(response.status==="ok"){$subtotal=''+response.subtotal+'';$('#sub_total-'+$id).html($subtotal);$('#grandtotal').html(response.grandtotal);$('#totalsubTotal').html(response.totalsubTotal);$('#mydiscount').html(response.discount);$('#grandtotal').html(response.totalgrandTotal)}if(response.status==="error"){}},error:function(response){alert(response)}})});$('.qtyplus').click(function(){var currentVal=parseInt($(this).prev('.text_fields2').val());if(!isNaN(currentVal)){$(this).prev('.text_fields2').val(currentVal+1)}else{$('.text_fields2').val(1)}});$(".qtyminus").click(function(){var currentVal=parseInt($(this).next('.text_fields2').val());if(!isNaN(currentVal)&&currentVal>1){$(this).next('.text_fields2').val(currentVal-1)}else{$(this).next('.text_fields2').val(1)}});$('#download_form_request').submit(function(evt){evt.preventDefault();var $form=$(this);$.ajax({type:$form.prop('method'),url:$form.prop('action'),data:$form.serialize(),dataType:"json",traditional:!0,success:function(response){if(response.status==="ok"){Custombox.close();$("#download_form").css("display","none");window.location=response.url+"?email="+response.email+"&code="+response.code+"&vendor="+response.vendor}},error:function(response){debugger;alert(response.d)}})})});$(document).ready(function(){$('input[type="checkbox"]').click(function(){if($(this).prop("checked")==!0){$("#buynowa").show();$("#buynowd").hide()}
else if($(this).prop("checked")==!1){$("#buynowa").hide();$("#buynowd").show()}})});$("#payBtn").click(function(){$url="https://www.octanetworks.com/main/cart/stripeemail";$.ajax({type:"POST",url:$url,dataType:"json",traditional:!0,})});$(document).on('change','#countryList',function(){$id=$("#countryList").val();if($id==="null")
{$("#cert_dropdown").slideUp("slow");return}
$url=$("#countryList").data("url");$.ajax({type:"POST",url:$url,data:{id:$id},dataType:"json",traditional:!0,success:function(response){if(response.status==="ok"){if(!$.isEmptyObject(response.states))
{$html='<select name="state" class="form-control"><option value="">Select State</option>';$.each(response.states,function(key,value){$html+="<option value="+value.id+">"+value.name+"</option>"});$html+="</select>";$("#lstates").html($html)}}},error:function(response){debugger;alert(response.d)}})});window.onload=function(){var $recaptcha=document.querySelector('#g-recaptcha-response');if($recaptcha){$recaptcha.setAttribute("required","required")}};function isNumberKey(evt){var charCode=(evt.which)?evt.which:evt.keyCode
if(charCode>31&&(charCode<48||charCode>57))
return!1;return!0}
$("#myModal").on('hidden.bs.modal',function(e){$("#myModal iframe").attr("src",$("#myModal iframe").attr("src"))});var current_url=window.location.pathname.split("/");var current_control=current_url[2];console.log(current_control);if(current_control=="exam"){$('.collapsed').collapse({toggle:!0})
var allPanels=$('.panel-collapse').hide();$('.topics-accordion .panel-title').click(function(){console.log('clicked');allPanels.slideUp();$('.topics-accordion #tab_close').removeClass('fa-minus');$('.topics-accordion #tab_close').addClass('fa-plus');$(this).parent().next().slideDown();$(this).children('#tab_close').removeClass('fa-plus');$(this).children('#tab_close').addClass('fa-minus');return!1})}